<!-- Footer -->
<div>
    <hr class="w-full border-t-1 border-white">
</div>
<footer class="text-green-600 flex flex-col items-center justify-center md:flex-row md:justify-between px-8 py-4 bg-custom-green text-shadow-black">
    <div class="flex items-center">
        <i class="fa fa-phone mr-2 text-4xl shadow-custom"></i><a class="text-xl font-bold"> Contacto 662 789
            611</a>
    </div>
    <div class="flex items-center mt-4 md:mt-0 md:ml-auto space-x-4">
        <span class="text-xl font-bold mr-2">Redes Sociales</span>
        <a class="text-green-600 text-4xl"><i class="fa-brands fa-facebook"></i></a>
        <a class="text-green-600 text-4xl"><i class="fa-brands fa-square-instagram"></i></a>
        <a class="text-green-600 text-4xl"><i class="fa-brands fa-linkedin"></i></a>
    </div>
    <div class="mt-4 md:hidden">
        <hr class="w-full border-t-1 border-white">
    </div>
</footer>
