
<!-- Footer -->
<div>
    <hr class="w-full border-t-1 border-white">
</div>
<footer class="text-green-600 flex flex-wrap justify-between px-8 py-4 bg-custom-green text-shadow-black m-4">
    <div class="flex items-center mb-2 md:mb-0">
        <i class="fa fa-phone mr-2 text-4xl shadow-custom"></i><a class="text-xl font-bold"> Contacto 662 789
            611</a>
    </div>
    <div class="flex items-center space-x-4">
        <span class="text-xl font-bold mr-2">Redes Sociales</span>
        <a class="text-green-600 text-4xl"><i class="fa-brands fa-facebook"></i></a>
        <a class="text-green-600 text-4xl"><i class="fa-brands fa-square-instagram"></i></a>
        <a class="text-green-600 text-4xl"><i class="fa-brands fa-linkedin"></i></a>
    </div>
</footer>

<div>
    <hr class="w-full border-t-1 border-white m-2">
</div>