
    <!-- Define la codificación de caracteres -->
    <meta charset="UTF-8">
    <!-- Define el autor del documento -->
    <meta name="author" content="Javier">
    <!-- Define el programa con el que se ha generado el documento -->
    <meta name="generator" content="NetBeans 21">
    <!-- Define el copyright del documento -->
    <meta name="copyright" content="DWES">
    <!-- Define el comportamiento de los buscadores -->
    <meta name="robots" content="index, follow">
    <!-- Define las palabras claves del contenido del documento -->
    <meta name="keywords" content="GestoCar">
    <!-- Define una breve descripción del sitio -->
    <meta name="description" content="Programa para la gestión del uso diario del coche">

