
<div>
    <hr class="w-full border-t-1 border-white">
</div>
<nav class="bg-custom-green flex flex-wrap justify-evenly p-6">
    <div class="flex items-center">
        <img src="IMG/logoConcesionario.png" alt="Logo" class="h-20 w-20">
    </div>
    <div class="text-center">
        <span class="text-shadow-black text-green-600 text-3xl md:text-5xl font-bobby-jones">GESTOCAR, Gestiona tus veh&iacute;culos de forma c&oacute;moda</span>
    </div>
</nav>
<div>
    <hr class="w-full border-t-1 border-white">
</div>

